env:
  global:
    - CODECOV_TOKEN="47c832fb-b4e7-4987-b90e-4ffe8bcf0acc"

language: java

before_install:
 - chmod +x gradlew

os: linux
dist: trusty
jdk: openjdk11

script:
  - ./gradlew clean build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
